# Generated by Django 5.2.11 on 2026-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='lineup_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
