# Generated by Django 5.2.11 on 2026-03-05 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0002_pick_lineup_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draftapp.draft')),
                ('offered_picks', models.ManyToManyField(related_name='offered_in_trades', to='draftapp.pick')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_trades', to=settings.AUTH_USER_MODEL)),
                ('requested_picks', models.ManyToManyField(related_name='requested_in_trades', to='draftapp.pick')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
