# Generated by Django 5.2.11 on 2026-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftapp', '0003_tradeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorder',
            name='formation',
            field=models.CharField(default='4-3-3', max_length=15),
        ),
    ]
